import type { DomainConfig } from "../../types";

export const selfEvolutionDomain: DomainConfig = {
    id: "self-evolution",
    title: "Self-Evolution & Security",
    description: "Monitor autonomous recon gathering, security audits, and agent-generated Pull Requests.",
    operations: [
        {
            id: "get_active_recon",
            title: "Active Recon & Security Strings",
            description: "Get the status of currently running intelligence gathering or hacking loops.",
            method: "GET",
            path: "/v1/operations/hub"
        },
        {
            id: "list_prs",
            title: "Evolution Pull Requests",
            description: "View pending self-improvement PRs generated by the heuristic engine.",
            method: "GET",
            path: "/v1/improvements"
        },
        {
            id: "trigger_security_audit",
            title: "Trigger Security Audit",
            description: "Force the agent to begin a vulnerability mapping on the local boundaries.",
            method: "POST",
            path: "/v1/outcomes/improvements",
            defaultBody: JSON.stringify({
                metric_id: "security_audit_local",
                context: "Triggered from Self-Evolution dashboard"
            }, null, 2)
        }
    ]
};
